### ISSUE TITLE
Dynamic top-level menus

### ISSUE THREAD

**Issue by joewing** [joewing/jwm#221] opened 2015-09-03 13:59 UTC
Currently it is only possible to have dynamic menus as members of a menu.  It would be nice to have RootMenu be a dynamic menu.  See issue #203.

**Comment by Israel-** [comment] 2015-09-03 22:23
If include could be dynamic this could solve the issue as well.  simply triggering the equivalent of  jwm -reload each time the menu is access would be sufficient to solve this.
```<Include dynamic=true>exec:my-menu</Include>```
If this is a more simple method of addressing this, I think it would be great

**Comment by joewing** [comment] 2015-09-03 22:26
I don't really know what it would mean for "Include" to by dynamic.  How would JWM know when to re-read the include?  Dynamic menus are possible since JWM reloads them each time they are accessed.

**Comment by Israel-** [comment] 2016-06-09 01:18
Hi @joewing 
I forgot to reply to this...
```xml
<Include dynamic=true>exec:my-menu</Include>
```
Basically Include shows a top level menu
Dynamic creates things each time, but is a sub menu.
So using Include dynamic=true was simply to express this.
I suppose something like
```xml
<Dynamic level="root">exec:jwm-menu</Dynamic>
``
Would be better, and more clear.
default could be submenu, as it is now.

**Comment by Israel-** [comment] 2017-01-25 04:22
@joewing @roandbox 
I really like this idea, however I have some serious issues when using it.
 * I cannot select items with a mouse (keyboard navigation works) like in a normal menu (clicking on an item often works, but not in every circumstance)
 * if I click outside the menu it does not disappear and JWM is forever unresponsive

**Comment by roandbox** [comment] 2017-01-25 05:45
Please write a fragment of the setting file for  dynamic menu

**Comment by Israel-** [comment] 2017-01-26 02:15
```xml
<RootMenu onroot="7" dynamic="exec:jwm-places||jwm-places-bash" />
```
Does your testing allow choosing items via mouse, or clicking outside the menu to close it?

**Comment by Israel-** [comment] 2017-01-26 14:13
@joewing I have been hacking around in parse.c and got the menu to act normally by changing the very end of:  Menu *ParseMenu(const TokenNode *start)
```c
   value = FindAttribute(start->attributes, DYNAMIC_ATTRIBUTE);
   if(value){
      menu->dynamic = CopyString(value);
      menu = ParseDynamicMenu(value);
   }
   else{
      menu->items = NULL;
      ParseMenuItem(start->subnodeHead, menu, NULL);
   }
```
But I cannot figure out how to make the menu generate new each time dynamically.
By adding the bit of code I did it now shows up allows mouse navigation and does not hang JWM.
What controls when a menu is re-parsed, like with a <Dynamic> tag?

**Comment by roandbox** [comment] 2017-01-26 16:34
> `<RootMenu onroot="7" dynamic="exec:jwm-places||jwm-places-bash" />`
@Israel- It is works without problems on the last commit.

**Comment by Israel-** [comment] 2017-01-26 20:51
@roandbox I just made a clean clone and install, and I am back to the issue I initially described.
The menu freezes.  The mouse cannot navigate it, and if I click outside of it I crash JWM.
My addition (above) makes the menu responsive and accessible to the mouse, but it is no longer dynamic.
I also added the menu in a <Dynamic> tag in a separate menu for the desktop... it works fine there.

My initial test was of the latest commit, I for some reason thought you may have pushed a fix.

**Comment by Israel-** [comment] 2017-01-26 20:54
What part of the code controls when a menu is shown?  I know the PatchMenu code does the job to recreate the Dynamic menus, and the window menus, etc... but only for a sub menu.
I have added my hack into a number of places and have not had any significant change to make it always redraw, as well as function.

**Comment by roandbox** [comment] 2017-01-28 17:00
@Israel-  Can you add a core dump for crash of JWM?

**Comment by joewing** [comment] 2017-01-29 19:56
@Israel- I am unable to reproduce this.  Is there a minimal, self-contained shell script you can provide that, when used as the dynamic menu, causes the problem?  Here's what I'm using:

```bash
#!/bin/bash

echo "<JWM>"
echo "<Program label=\"xterm $RANDOM\">xterm</Program>"
echo "<Separator/>A"
echo "<Restart/>"
echo "<Exit/>"
echo "</JWM>"
```

And in `~.jwmrc`:
```xml
<RootMenu onroot="1" dynamic="exec:$HOME/genmenu.sh"/>
```

This works exactly as I would expect, with a different random number each time and I'm able to click or use the keyboard to select items, etc.

As far as the code is concerned, in `root.c`, there is a function called `ShowRootMenu`, which handles setting up loading the dynamic menu when needed.  There were problems with how this was originally implemented, so are you sure you're using a recent version?

**Comment by Israel-** [comment] 2017-01-29 23:21
@joewing It is very odd that I have this issue.
I JUST rebuilt, and used your exact code.
And I get very odd artefacts.  It does not say "xterm ***n***" it has "/"
And it will hide the lower menu items
The " is causing issues.
So this works fine
```bash
#!/bin/bash
echo "<JWM>"
echo '<Program label="cool">xterm</Program>'
echo "<Separator/>A"
echo "<Restart/>"
echo "<Exit/>"
echo "</JWM>"

```

I am not sure how you cannot reproduce this issue...
```bash
~/git/jwm$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

~/git/jwm$ which jwm
/usr/local/bin/jwm

##in ~/git/jwm/src/
1047440 Jan 29 16:44 jwm*
##in /usr/local/bin/
1047440 Jan 29 16:57 jwm*

```
Perhaps the menu cannot handle having many sub-directories?
My places menu goes one directory deep, reads the XDG user dirs, and reads the gtk bookmarks to generate a menu of 'Places' like many other DE do.
It works well as an include, and shows no errors via `jwm -p` nor anything in my error logs
perhaps a test with many submenu items..
A slimmed down version of my menu (still crashes JWM)
has 10 submenus and 2 programs
one submenu has over 50 items, one over 30 and the rest are 15 or less (all the way down to 1)

could JWM be unable to handle that many menus being generated?
Or, could it be the TIME it takes to generate the menu.

My places menu program does not cache itself, as it is fairly quick

real	0m0.061s
user	0m0.024s
sys	0m0.004s
And this has problems...
The other menu
jwm-menu caches itself, and takes less time (unless regenerating)
real	0m0.010s
user	0m0.004s
sys	0m0.004s
And when I tested it as a dynamic root menu it preformed a bit better...
Both do quite well in a <Dynamic> tag, so I am unable to discern why this always fails.

**Comment by roandbox** [comment] 2017-01-30 06:08
@Israel-  Run the command in console:
` jwm-places||jwm-places-bash > menu.txt`
and attach the file "menu.txt`" to the issue

**Closed** 2017-07-08 17:11 UTC
Labels: enhancement
