### ISSUE TITLE
bug: restarting jwm with chromium on another desktop causes chromium to dissapear

### ISSUE THREAD

**Issue by nixingizgood** [joewing/jwm#340] opened 2016-10-19 07:13 UTC
1. open chromium on desktop 2
2. switch to desktop 1
3. restart jwm
4. switch to desktop 2

chromium disappears, including from the task list. Yet the process still exists ...

**Comment by theUncanny** [comment] 2016-11-07 09:19
Hi @nixingizgood!

I tried to reproduce the issue, but, in my system, Chromium not disappears.

My JWM `group` Chromium config:

```xml
  <Group>
    <Name>chromium-browser</Name>
    <Class>chromium-browser</Class>
    <Option>desktop:2</Option>
    <Option>fixed</Option>
    <Option>pignore</Option>
    <Option>iignore</Option>
    <Option>nofocus</Option>
  </Group>
```

* JWM version `2.3.7` (git, 12 oct 2016)
* Chromium version `53.0.2785.143` on Ubuntu 16.04.1 LTS

**Comment by nixingizgood** [comment] 2016-11-07 09:32
Would you mind removing all the options you added and trying again?

**Comment by theUncanny** [comment] 2016-11-07 09:47
Yeah, no problem. I removed my Chromium `group` option and saved the config, launch Chromium on desktop 2, switched to other desktop, restarted JWM and switched to desktop 2, but Chromium not disappears.

**Comment by joewing** [comment] 2017-02-12 23:48
I was able to reproduce this only when "system title bar and borders" were disabled.  The problem was that JWM didn't re-map the window when restarting or exiting, so the window would be lost.  This should be fixed as of snapshot 1582.

**Closed** 2017-07-08 16:07 UTC
Labels: bug
