### ISSUE TITLE
Problems with Wine & Java apps

### ISSUE THREAD

**Issue by wdlkmpx** [joewing/jwm#198] opened 2015-08-05 15:28 UTC
Using latest git.

When switching between apps in the taskbar, JWM ignores Wine & Java apps.

Wine & Java taskbar buttons don't get the focus, weird. When clicked, the main window is shown, but the titlebar still has the inactive color. Besides that, it's possible to work with those apps. But somehow the focus remains in other window.

Tray icons in Java: ok.
Tray icons in Wine: strange behavior, disappears when an application is minized to tray. Have to kill the app.

This is happening in an old system based on Ubuntu Precise, I haven't tested in another distro/version.

I remember that s871 didn't have this issue, something that I noticed appeared afterwards...

JWM is practically complete, I think this and the LXTerminal issue are the only ones worth taking care of...

**Comment by joewing** [comment] 2015-08-05 22:55
This should be fixed now (in snapshot 1219).  It fixed the issue with Java programs for me, but I haven't tried wine.

**Comment by wdlkmpx** [comment] 2015-08-06 01:30
Yes, the issue with taskbar buttons and window focus is fixed.

Java: ok (jdownloader)
Wine: semi ok (colors, chmdecoder,rufus,renamer,etc)

However, Wine apps that implement a Tray icon still have that problem, (emule, foobar2000, utorrent2.2.1).  The pointer disappears when is over the tray icon. No context menu.

I tested these versions:
wine-1.6.2-i486_v2.1-racy
wine-1.7.47-i486_v2.1-racy

It's not a big deal, I know wine is problematic, I'm quite happy with these results...

**Comment by graemeg** [comment] 2015-08-15 11:05
I can confirm this issue with 2.3.1 and with s1230 under FreeBSD 10.1.  I'm using WINE 1.7.33 and trying to run EditPad Pro 7 (a Windows text editor), but I simply can't get focus to the application. When I try and type in the editor, the keyboard input goes to the other focused application, not to EditPad Pro.  This bug means I would have to revert to 2.2.2 which was the previous JWM I used and that was working 100%.

I just tried with other Windows applications too. They all behave the same as EditPad Pro - I simply can't get focus to them - mouse or keyboard.

**Comment by wdlkmpx** [comment] 2015-08-20 03:02
Due to popular demand I reopen this issue.


----
WINE
----

Some wine apps (those with a tray icon) don't get focus in taskbar.

Keyboard, mouse.. ok. But the window title remains with the inactive color... my brother (he is using Arch Linux) told me about the focus issues with Wine.

Tray icon is unclickable, mouse pointer disappears when it's over it. Though in foobar2000 it seems to respond sometimes.

It looks that lxpanelx can handle that situation, but there are rendering issues.

I also compiled latest version of gdb, but I still can't figure out how to use it, there are is no info output when I attach it to jwm's pid.

That's my report.

**Comment by joewing** [comment] 2015-08-20 12:17
Unfortunately, I don't have wine installed (well, fortunately, from my perspective), but it sounds like the window is mapped with WM_HINTS indicating that the window does not accept input focus and without WM_TAKE_FOCUS set in WM_PROTOCOLS.  In this case JWM does not give the window focus because the window claims it does not want focus.  The same thing happens with xclock and xvkbd, for example.  With a program like xvkbd, it is certainly not desirable to give the window focus and this is the only way JWM knows not to give the window focus.

**Comment by graemeg** [comment] 2015-08-20 12:26
Are you suggesting that WINE (and apparently Java) is setting the wrong window hints? Something in JWM must have changed though, because in JWM 2.2.2 it works, switching to 2.3.1 it doesn't.  The version of WINE has not changed on my system, I'm only switch between JWM versions.  I haven't tested 2.3.0 yet.

Seeing as I can reproduce the issue, and compiling JWM on my FreeBSD system is simple enough, maybe I can use **git bisect** to find out exactly what commit causes this problem.

I'm assuming the build instructions for a release JWM archive is the same instruction I would use when compiling JWM from a git checkout?  Sorry if this is a dumb question, but I'm not a C/C++ developer.

**Comment by joewing** [comment] 2015-08-20 13:08
My suspicion is WINE is setting WM_HINTS to say "Client accepts input or input focus: False" without setting WM_TAKE_FOCUS in WM_PROTOCOLS.  Running xprop and clicking on the window should show that.  I would be interested to see the output to see if there's anything JWM can do to attempt to identify that it should focus the window.

This is a change in behavior for JWM (to fix issue #185) in that JWM will no longer assign focus to such windows.

**Comment by graemeg** [comment] 2015-08-20 13:18
Here is the output for xwininfo and xprop. I tested with two different Windows applications I run under WINE. Both gave the same issue with JWM later than v2.2.2. From what I can see, both have class type as InputOutput which is expected, and both have WM_TAKE_FOCUS set. So I don't see a problem from WINE's side.

Hope this helps...

**PINS**
```
[~]$ xwininfo

xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x3400005 "Graeme_Geldenhuys.pins - PINs v.4.50.0.86"

  Absolute upper-left X:  498
  Absolute upper-left Y:  118
  Relative upper-left X:  5
  Relative upper-left Y:  24
  Width: 670
  Height: 595
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x3200001 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +498+118  -1392+118  -1392-727  +498-727
  -geometry 670x595+498+118

[~]$ xprop
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_SHADE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_STICK, _NET_WM_ACTION_BELOW, _NET_WM_ACTION_ABOVE
_NET_FRAME_EXTENTS(CARDINAL) = 5, 5, 24, 5
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR
_NET_WM_ICON(CARDINAL) = 	Icon (16 x 16):
	                
	                
	          ████  
	         █░░░░█ 
	█████████░░░░░░█
	█░░░░░░░░░░░██░█
	█░█░█░█░█░░░██░█
	 ████████░░░░░░█
	         █░░░░█ 
	         ░████░░
	░░░░░░░░░░░░  ░░
	░░░░░░░░░░░░  ░░
	 ░░░░░░░░░░░░░░░
	         ░░░░░░ 
	          ░░░░  
	                


_NET_WM_NAME(UTF8_STRING) = "Graeme_Geldenhuys.pins - PINs v.4.50.0.86"
WM_ICON_NAME(STRING) = "Graeme_Geldenhuys.pins - PINs v.4.50.0.86"
WM_NAME(STRING) = "Graeme_Geldenhuys.pins - PINs v.4.50.0.86"
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
		Initial state is Normal State.
		bitmap id # to use for icon: 0x3200055
		bitmap id # of mask for icon: 0x3200057
		window id # of group leader: 0x3400001
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
WM_TRANSIENT_FOR(WINDOW): window id # 0x3400001
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x3e, 0x7e, 0x62ffb440, 0x10082
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 694, 149
		window gravity: Static
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x3200023
XdndAware(ATOM) = ATOM
_NET_WM_PID(CARDINAL) = 87466
WM_LOCALE_NAME(STRING) = "en_GB.UTF-8"
WM_CLIENT_MACHINE(STRING) = "graeme-desktop"
WM_CLASS(STRING) = "pins.exe", "Wine"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING, WM_TAKE_FOCUS

```

**EditPad Pro v7**
```
[~]$ xwininfo

xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x3800013 "EditPad Pro 7 - [*Untitled 1]"

  Absolute upper-left X:  232
  Absolute upper-left Y:  24
  Relative upper-left X:  5
  Relative upper-left Y:  24
  Width: 1524
  Height: 1313
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x3000001 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +232+24  -804+24  -804-103  +232-103
  -geometry 1524x1313+232+24

[~]$ xprop
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_SHADE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_STICK, _NET_WM_ACTION_BELOW, _NET_WM_ACTION_ABOVE
_NET_FRAME_EXTENTS(CARDINAL) = 5, 5, 24, 5
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR
_NET_WM_ICON(CARDINAL) = 	Icon (32 x 32):
	                                
	                                
	           ░▒▓▓▓▓▓▓▒░           
	         ▒▓▓▒▒▒▒▒▒▒▒▓▓▒         
	       ░▓▒░░░░▒▒▒▒▒▒▒▒▓▓░       
	      ░▓▒▒░▒░░░░░░░░▒▒▒▒▓░      
	     ░▓▒▒▒░░ ░ ░ ░░░░░░░▒▓▒     
	    ░▓░▒▒░ ░░░░░░░░ ▒ ░▒░▒▓░    
	    ▓▒▒▒▒  ░ ░░░░░░░░ ░▒▒░▒▓░   
	   ▒▒░▒▒░        ░░░░░░░░▒▒▓▒   
	   ▓░▒▒▒░             ░ ▒░▒▓▓░  
	  ░▓░▒▒░               ░▒░▒▓▓░  
	  ▒▒░▒▒             ░░░▒░░▒▓▓▒░ 
	  ▓░░▓░░░         ░░░░░▒ ░▒▒▒▓░ 
	  ▓░▒▒░░░░    ░░░░░░░░▒░ ░▒▒▒▓░ 
	  ▓░▓░░░░░░░  ░░░░░░░░▒  ░▒▒▒▓░ 
	  ▓▒▒░░░░░░░░░░░░░░░░▒▒  ░▒▒▒▓░ 
	  ▓▓░░░░░░░░░░░░░░░░░▓   ░▒▓▒▓░ 
	  ▓▒░░░░░░░░░░░░░░░░▒▒░  ░▒▓▒▓░ 
	 ░▒░░░░░░░░░░░░░░░░░▓░  ░░▒▓▓▒░ 
	 ▒▒░░░░░░░░░░░░░░░░▒▒░  ░░▒▓▓▒░ 
	░▒░░░░░░░░░░░░░░░░░▓░   ░░▒▒▓░░ 
	▒░░░░░░░░░░░░░░░░░▒▒░░  ░▒▒▓▒░  
	▒░░░▒░░░░░░░░░░░░░▓░░   ░▒▒▓░░  
	▒▓▒▒░▒░░░░░░░░░░▒▒▒ ░  ░░▒▓▒░   
	 ░▒▒▒▒▒▒░░░░▒░░▒░▒░░░  ░▒▓▒░    
	   ░░░▒▓▓▒▒░░▒▒▒▒▒  ░ ░▒▓▒░░    
	       ░▓▓▒▒▓▒▒░▒░░░░▒▓▓▒░░     
	        ░▒▓▓▒▒▒▒▒░▒▒▓▓▒░░       
	          ░░▒▓▓▓▓▓▓▒▒░░░        
	            ░░░░░░░░░░          
	                                


_NET_WM_NAME(UTF8_STRING) = "EditPad Pro 7 - [*Untitled 1]"
WM_ICON_NAME(STRING) = "EditPad Pro 7 - [*Untitled 1]"
WM_NAME(STRING) = "EditPad Pro 7 - [*Untitled 1]"
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
		Initial state is Normal State.
		bitmap id # to use for icon: 0x3000238
		bitmap id # of mask for icon: 0x300023a
		window id # of group leader: 0x3800002
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
WM_TRANSIENT_FOR(WINDOW): window id # 0x3800002
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x3e, 0x7e, 0x63139440, 0x2022c
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 454, 58
		window gravity: Static
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x3000027
XdndAware(ATOM) = ATOM
_NET_WM_PID(CARDINAL) = 87547
WM_LOCALE_NAME(STRING) = "en_GB.UTF-8"
WM_CLIENT_MACHINE(STRING) = "graeme-desktop"
WM_CLASS(STRING) = "EditPadPro7.exe", "Wine"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING, WM_TAKE_FOCUS
```

**Comment by joewing** [comment] 2015-08-20 13:21
Well, that makes it easy. JWM must be only looking at WM_HINTS and not WM_PROTOCOLS to determine if it should assign focus.  I'll have a fix soon.  Thanks!

**Comment by yetanothergeek** [comment] 2015-08-20 15:53
I don't know if it is relevant here, but there is a setting in winecfg->Graphics:
  [X] Allow the window manager to control the windows
(and a few other settings that might have some effect)

**Comment by graemeg** [comment] 2015-08-20 16:17
Hi Jeff - Incidentally I have that option enabled. I guess it is a default WINE option. Still didn't make a difference here though.

**Comment by joewing** [comment] 2015-08-20 23:47
So the issue with JWM not checking WM_PROTOCOL was what was causing the Java issue, and that was fixed in snapshot 1219 (it resolves the problem for me with Java apps).  This would be broken in 2.3.1.

I suppose it could be the case that an application claims to use TAKE_FOCUS and then doesn't actually grab the focus.  JWM used to assign the focus to the top-level window no matter what, now JWM only sends a TAKE_FOCUS client message.  If this is happening, the window will appear to be active (have the active window color), but key presses will go elsewhere.  I'll attempt to fix this issue by making JWM assign the focus as before (should be safe to do I think...).

**Comment by Israel-** [comment] 2015-08-20 23:51
@joewing Do you think this broke fixing the issue with virtualbox?  If there is no way to support both, I would say wine and java are more common for the average user, and I can work around the keyboard issues with virtualbox

**Comment by joewing** [comment] 2015-08-20 23:56
I think it should be possible to make this work everything, it's just a little tricky.

So it turns out JWM used to assign focus to the parent window if TAKE_FOCUS was set and WM_HINTS specified no input focus. I don't know if that is an issue, but it was wrong behavior (fixed in 1242).

**Comment by Israel-** [comment] 2015-08-21 01:36
Ah ok... I am updating my PPA now, I will test it and see if virtualbox still performs the same

**Comment by wdlkmpx** [comment] 2015-08-21 01:38
There is something going on with wine.. something totally insane..

After the last commit, some other apps in the taskbar get focus... ReNamer, utorrent 2.2.1 and eMule.  However (in eMule and utorrent) if a dialog appears (settings, etc), the app reverts to its previous behavior.. JWM ignores the app again (in the taskbar).

The combination Openbox + LXPanelX seem to overcome this issue just because of OpenBox, as LXPanelX also has issues with some Wine apps (can't receive focus in taskbar, completely ignores them)... so when pressing Alt + Tab, OpenBox shows a window showing all apps, just select one.

So.... my veredict is guilty. Wine is problematic...

**Comment by joewing** [comment] 2015-08-21 13:57
I think this should work better as of snapshot 1244.  JWM wasn't restoring it's internal view of which window has focus correctly when a client updated motif hints.  APparently wine applications update motif hints a lot.

There is still an issue with the dock.  I think that's due to the fact that JWM doesn't support the XEmbed protocol (http://standards.freedesktop.org/xembed-spec/xembed-spec-latest.html).

**Comment by wdlkmpx** [comment] 2015-08-21 16:23
Yes it's almost done, this is so exciting

**Comment by Israel-** [comment] 2015-08-23 12:07
JWM still lets VirtualBox have the keyboard in 1244, in all of the latest commits, I haven't had any regression.  I think 2.3.2 is going to be a great release for JWM.  The menus are better, icons are found automatically and there have been some really great bug fixes!
thanks @joewing

**Closed** 2015-08-26 00:50 UTC
Labels: bug

**Comment by graemeg** [comment] 2015-08-26 07:49
@joewing : Many thanks. I've tested with s1247 under FreeBSD, and my Windows applications now work perfectly. I also tested with a Java program, and that seems fine too. Thanks for all your effort. ;-)
