### ISSUE TITLE
Bug: separator in menu gets focus if navigated using the Up key

### ISSUE THREAD

**Issue by dumblob** [joewing/jwm#343] opened 2016-11-17 20:05 UTC
As the title says, separators in menus are getting focused if the menu is navigated with the keyboard `Up` arrow key.

**Comment by joewing** [comment] 2016-12-19 23:02
I'm not able to reproduce this.  I've tried opening a (root) menu with separators and then pressing the up arrow.  The behavior I see is the highlight goes up (wrapping at the top) and skips over the separators.  Is this an old version of JWM perhaps?

**Comment by dumblob** [comment] 2016-12-20 11:11
I'm sorry @joewing for forgetting to attach steps to reproduce (hint: you might remind us, leaky heads, to provide steps and materials to reproduce by ading a tiny GitHub Issue template in the repo settings).

Steps with materials and pointers how to reproduce the issue:

1. Ensure there is `<Separator/>` directive two or more times successively used at the very end of at least one (sub) menu. E.g.

~~~~
  <RootMenu onroot="3">
    <Menu icon="folder.png" label="Apps">
      <Program icon="gthumb.png" label="gThumb">gthumb</Program>
      <Program icon="gimp.png" label="Gimp">gimp</Program>
      <Separator/>
      <Separator/>
    </Menu>
  ...
~~~~

1. Run JWM, switch to the (sub)menu with the consecutive `<Separator/>` directives and press the `Up` key (or any key performing the `up` action - I have *vi* bindings, so it's `k` for me) until the separator gets focused or the menu navigation somehow screwed (e.g. jumping out of the submenu etc.).

**Comment by joewing** [comment] 2017-01-15 19:33
Thanks for reporting this!  It should be fixed in snapshot 1573.

**Closed** 2017-01-29 19:41 UTC
Labels: bug
