### ISSUE TITLE
Compton and terminal

### ISSUE THREAD

**Issue by holmeslinux** [joewing/jwm#216] opened 2015-08-20 02:41 UTC
hi all,
i am creating a Manjaro spin with JWM (in https://goo.gl/GcoAow), but i'm in problem. i am having problem with the compton, because it changes the color of the terminal window (sakura). with xterm does not occur this!

sakura: http://www.auplod.com/u/odapul5f9ea.png
xterm: http://www.auplod.com/u/ldpoua5f9eb.png

this is a bug?

vlw fwi, Holmes

**Comment by Israel-** [comment] 2015-08-20 02:51
Hi @holmeslinux I have the same issue in Ubuntu with sakura.
I also have another issue  #177
which makes an autohide Tray not have any icons visible.
Could you test to see if creating a Tray with autohide and a few TrayButtons disappears.

p.s. I am working on a similar project using Ubuntu as the base, maybe we can share some tools we use?  Point me to your ISO and I will try to build my JWM-settings-manager for manjaro if you like

**Comment by holmeslinux** [comment] 2015-08-20 02:59
the problem not only with sakura. already tested with other terminals. always change the window color. this problem does not happen with xterm!

great, we exchange information...

isos: http://goo.gl/t1oxbC
codes: https://goo.gl/eWXAlk

vlw fwi, Holmes

**Comment by joewing** [comment] 2015-08-28 23:16
I think this may be due to JWM using the wrong visual for frames.  If that's the case, it should be fixed in snapshot 1257.

**Comment by holmeslinux** [comment] 2015-08-28 23:57
this might be the problem and thanks for listening.

vlw fwi, Holmes :)

**Comment by Israel-** [comment] 2015-08-29 00:24
I'm updating my PPA and I'll test this.
@joewing do you think this will fix the issue with the autohide Tray not having icons when using compton?

**Comment by joewing** [comment] 2015-08-29 00:27
This doesn't fix the autohide issue, unfortunately.  I'm looking into that now.

**Comment by Israel-** [comment] 2015-08-29 00:29
Thanks Joe!!  JWM is by far the BEST supported (anything related to computers) ever!

**Comment by joewing** [comment] 2015-08-29 00:31
And I think the autohide issue might be fixed now.
I was able to reproduce a similar issue with xcompmgr, not sure if it's the same thing.

**Comment by Israel-** [comment] 2015-08-29 02:03
Yes!  Thanks Joe, I'll close the bug I opened about it!

**Comment by Israel-** [comment] 2015-08-31 12:09
There is a new issue that I think is related to this being fixed...
Opening FLUID (fltk user interface designer) will sometimes lock the screen up.
I can 'fix' the problem by dropping to a different TTY and then going back to my X TTY.  JWM still takes keyboard commands, but the screen does NOT redraw at all.
It happens with most any FLUID project I open, large or small.
It doesn't happen with blank ones or any of my random attempts to make a dummy file..
Most of the keyboard is locked, and the mouse as well.

However I can change the window position with my keyboard shortcuts for maxleft maxright maxtop maxbottom.   But if I do that then I completely lock up things and the TTY trick does not work.
I am using 1260

**Comment by joewing** [comment] 2015-10-28 01:09
Marking this as closed since I believe the original issue is fixed.  Is there still a problem with FLUID?  If so, please let me know or open another issue.

**Closed by joewing** 2015-10-28 01:09 UTC
Labels: bug
