### ISSUE TITLE
Keyboard shortcuts do not work

### ISSUE THREAD

**Issue by holmeslinux** [joewing/jwm#322] opened 2016-08-17 11:56 UTC
hello Joe,
when all your open windows are minimized, the keyboard shortcuts stop to work.

obs.: i'm using version JWM 2.3.5.

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment] 2016-08-17 15:11
hi all,
one thing i realize is that sometimes the keyboard shortcuts work.
but generally not work...

vlw fwi, Holmes :)

**Comment by ml-** [comment] 2016-08-18 09:03
Probably works after a JWM restart.

Related: https://github.com/joewing/jwm/issues/321

**Comment by holmeslinux** [comment] 2016-11-08 01:54
hi all,
this is still happening!

vlw fwi, Holmes :)

**Comment by Israel-** [comment] 2016-11-08 02:29
Hi @holmeslinux what is the output of `jwm -p`
It may be that you have something in your .jwmrc that is not working correctly.
This is especially true if you have a menu that is generated OR some of your startup commands do not function correctly and are included BEFORE your keyboard shortcuts.
You might also check your ~/.xsession-errors for JWM errors (or wherever your standard error catch all file is)

**Comment by holmeslinux** [comment] 2016-11-08 13:57
hi Israel,
i will see the output of the  jwm -p command and the contents of the xsession-errors file.

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment] 2016-11-08 19:52
with jwm -p no errors.
the file .xsession-errors is empty.

vlw fwi, Holmes :)

**Comment by 01micko** [comment] 2016-11-12 00:09
Are you using the `<Include>` correctly for your key config ?

**Comment by holmeslinux** [comment] 2016-11-12 08:09
yes, correct!

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment] 2016-12-10 23:56
hi all,
still I continue with this problem!

@joewing 

some guidance?

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment] 2016-12-23 23:11
by fatboy

> Busy testing this in a virtual machine. So freakin fast! Well done Holmes. Not sure if other users are experiencing the same "bug", but when I minimize all the windows in a workspace, my keyboard shortcuts stop working?

in https://forum.manjaro.org/t/manjaro-jwm-tempura-16-10-released/10616/48.

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment] 2017-01-08 21:52
hi guys
any suggestions to solve this?
even to raise and lower the sound via key
need to have an active window

@joewing  @technosaurus any solution?

vlw fwi, Holmes :)

**Comment by joewing** [comment] 2017-01-09 01:16
Unfortunately, I haven’t been able to reproduce this.  For example, I can minimize all windows (or just now open any) and switch desktops using JWM keybindings without any trouble.  Are you using something that manages the desktop perhaps (to provide icons etc?)?  If so, have you tried without that?  Can you provide a key binding from the JWM configuration that stops working?

**Comment by Israel-** [comment] 2017-01-09 02:01
@holmeslinux 
What version of JWM are you running?  Does this bug persist in the current snapshot?
Do you run something that could be stealing the keyboard focus?
@joewing could something like conky or gkrellm do this sort of thing?

**Comment by holmeslinux** [comment] 2017-01-09 20:05
hello all
here has nothing to manage the desktop.
the JWM version is 2.3.6.
the strange thing is that there are other users of the Manjaro JWM that has the same problem.
the desktop has 3 conkys.
JWM settings are here: https://github.com/holmeslinux/Manjaro-JWM/tree/master/jwm-overlay/etc/skel/.jwm. could you analyze my settings?

vlw fwi, Holmes :)

**Comment by joewing** [comment] 2017-01-15 20:27
@holmeslinux Can you make this happen with nothing other than JWM running (no conky or compositor, etc)?  If so, does it still happen with a minimal config, something similar to the default?

**Comment by holmeslinux** [comment] 2017-01-16 15:55
@joewing 
i disabled conky and compton

**now it works perfectly...**

perhaps conky and compton are affecting the use of keys

is it some bug?

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment] 2017-01-16 18:11
hi all
i activated the conky and deactivated the compton

**the keys worked...**

everything indicates is compton

vlw fwi, Holmes :)

**Comment by Israel-** [comment] 2017-01-16 23:30
@holmeslinux the StartupCommands tend to do really strange things in my experience.
The **ORDER** tends to really matter here.
So try putting compton at the very end and see if you still have the issue.

**Comment by holmeslinux** [comment] 2017-01-17 00:26
hello @Israel- 
nothing has changed
still the same thing!

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment] 2017-01-23 12:53
hi all
i came back to activate the conky
the key problem has returned
i think compton and conky affect JWM

what do you think, @joewing ?

vlw fwi, Holmes :)

**Comment by joewing** [comment] 2017-02-02 04:14
Does this happen with just conky or with just compton?
If it only happens with compton, it would be interesting to see if it happened if rounded window borders were disabled (setting `<Corner>0</Corner>` in `WindowStyle`).

**Comment by holmeslinux** [comment] 2017-02-02 12:01
@joewing 
the problem is with conky! when the conky is off the keys work perfectly.
but for me compton does this https://github.com/joewing/jwm/issues/341

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment] 2017-02-02 12:17
kkkkkkkkkkkkkkkkkkkkkkk...

leaving **corner zero** solved the problem https://github.com/joewing/jwm/issues/341

thank you @joewing 

vlw fwi, Holmes :)

**Comment by myself12345** [comment] 2017-03-10 13:24
I confirm : the problem is conky.
Solution : set override in conky setting file : 
'own_window_type   override'
if conky disseapear when you set wallpaper with pcmanfm, just restart conky
I think this bug can be closed as it's really due to conky

**Closed** 2017-07-13 23:55 UTC
